#!/system/bin/sh
#
# Dual Recovery for many Sony Xperia devices!
#
# Author:
#   [NUT]
#
# - Thanks go to DooMLoRD for the keycodes and a working example!
# - My gratitude also goes out to Androxyde for his sometimes briliant
#   ideas to simplify things while writing the scripts!
#
###########################################################################

set +x
_PATH="$PATH"
export PATH="/system/xbin:/system/bin:/sbin"

# Constants
PREPLOG="/data/local/tmp/XZDualRecovery/preperation.log"

# Function definitions

TEXECL(){
  echo "$*" >> ${PREPLOG}
  $* 2>&1 >> ${PREPLOG}
  _RET=$?
  echo "RET=${_RET}" >> ${PREPLOG}
  return ${_RET}
}

EXIT2CM(){
	export PATH="${_PATH}"

	exec /system/bin/chargemon.stock
	exit 0
}

BUSYBOX="/system/xbin/busybox"

${BUSYBOX} blockdev --setrw $(${BUSYBOX} find /dev/block/platform/msm_sdcc.1/by-name/ -iname "system")

# We can actually safely asume a busybox exists in /system/xbin (as XZDualRecovery installs one there)
${BUSYBOX} mount -o remount,rw rootfs /

${BUSYBOX} mkdir /data/local/tmp/XZDualRecovery
${BUSYBOX} mount -o remount,ro rootfs /

# remove old log
${BUSYBOX} rm -rf /data/local/tmp/XZDualRecovery/preperation.log

mount -o remount,rw rootfs /
mount -o remount,rw /system

mount -t securityfs -o nosuid,nodev,noexec securityfs /sys/kernel/security
mkdir -p /sys/kernel/security/sony_ric
chmod 755 /sys/kernel/security/sony_ric
echo "0" > /sys/kernel/security/sony_ric/enable

${BUSYBOX} cp ${BUSYBOX} /sbin/

# Create a symlink for each of the supported commands
for sym in `${BUSYBOX} --list`; do
	${BUSYBOX} ln -sf ${BUSYBOX} /system/xbin/$sym
done

export PATH="/system/xbin"

mount -o remount,ro rootfs /
mount -o remount,ro /system

if [ ! -d "/system/etc/init.d" ]; then
	mkdir /system/etc/init.d
fi

########
#
#
# Preperations all done, lets continue to recovery!
#
#
#######################################################################

EXIT2CM
